### ISSUE TITLE
some paper may interested

### ISSUE THREAD

**Issue by hcji** [JosieHong/awesome-mass-spectrometry-ml#1]
**spectral prediction**
10.1021/acs.analchem.3c02413
http://arxiv.org/abs/2306.16085
10.1038/s42004-023-00932-3
10.12688/f1000research.52549.1
10.1101/2023.07.06.547963

**rt prediction**
10.1093/bioinformatics/btae084
10.1016/j.chroma.2023.464439
10.26434/chemrxiv-2023-1mq73
10.1021/acs.analchem.1c03250
10.1007/s00216-020-02905-0
10.1021/acs.analchem.0c04071

**formula prediction**
10.1021/acs.jcim.3c01082
10.1038/s42256-023-00708-3

**similarity prediction**
10.1021/acs.analchem.8b05405
10.1038/s41467-023-39279-7
10.1101/2024.03.25.586580
10.1186/s13321-021-00558-4
10.1371/journal.pcbi.1008724
10.1021/acs.analchem.3c00260

**ccs prediction**
10.1038/s42004-023-00939-w

**Comment by josiehong** [comment]
Thank you for the suggestions! So far, the preprints without peer review are not contained in this list, and the others have been updated.
